name: chained failure

on:
  workflow_dispatch:
    inputs:
      my_var:
        required: false
        default: 'None'

jobs:
  set-variable:
    runs-on: ubuntu-latest
    outputs:
      my_var: "${{ steps.set_var.outputs.my_var }}"

    steps:
      - id: set_var
        shell: python
        run: |
          import os
          
          my_var = os.environ["MY_VAR"]
          
          if my_var == 'None':
              print(f"::set-output name=my_var::{[]}")
          else:
              print(f"::set-output name=my_var::{my_var}")
        env:
          MY_VAR: ${{ github.event.inputs.my_VAR }}

  job-that-fails:
    needs: [set-variable]
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          assert False

  job-that-always-runs:
    needs: [job-that-fails]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "This job always runs"

  last-job:
    needs: [set-variable, job-that-always-runs]
    if: always() && needs.job-that-always-runs.result == 'success' && needs.set-variable.outputs.my_var != '[]'
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "This job runs after job-that-always-runs has completed"
          echo "MY_VAR: ${MY_VAR}"
        env:
          MY_VAR: needs.set-variable.outputs.my_var
