name: Comment repo2docker image name to a Pull Request

on:
  workflow_run:
    workflows:
      - "Testing r2d-action with pr-target trigger"
    types:
      - completed

jobs:
  post-image-name:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - run: python src/workflow_run_event.py
        env:
          WORKFLOW_RUN: "${{ github.event.workflow_run }}"
