name: chained failure

on:
  workflow_dispatch:

jobs:
  job-that-fails:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          assert False

  job-that-always-runs:
    needs: [job-that-fails]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "This job always runs"

  last-job:
    needs: [job-that-always-runs]
    if: always() && needs.job-that-always-runs.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "This job runs after job-that-always-runs has completed"
