name: Comment on a merged PR

on:
  push:
    branches:
      - main

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      continue-workflow: ${{ steps.get-pr-number.outputs.continue_workflow }}
      pr-number: ${{ steps.get-pr-number.outputs.pr_number }}
    steps:
      - name: Echo commit message
        id: get-pr-number
        shell: python
        run: |
          import re

          commit_msg = r"""${{ github.event.head_commit.message }}"""
          print(f"::set-output name=continue_workflow::{'Merge pull request' in commit_msg}")

          match = re.search('(?<=#)[0-9]*', commit_msg)
          if match is not None:
              pr_number = match.group(0)
              print(f"::set-output name=pr_number::{pr_number}")
          else:
              print(f"::set-output name=pr_number::{None}")

  add-pr-comment:
    runs-on: ubuntu-latest
    needs: [get-pr-number]
    if: needs.get-pr-number.outputs.continue-workflow == 'True'
    steps:
      - name: Comment on closed PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var PR_NUMBER = process.env.PR_NUMBER;

            github.rest.issues.createComment({
              issue_number: ${PR_NUMBER},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:rocket:`
            })
        env:
          PR_NUMBER: "${{ needs.get-pr-number.outputs.pr-number }}"
