name: Comment on a merged PR

on:
  push:
    branches:
      - main

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo commit message
        shell: python
        run: |
          import re

          commit_msg = r"""${{ github.event.head_commit.message }}"""
          print(commit_msg)
          print("Merge pull request" in commit_msg)

          match = re.search('(?<=#)[0-9]*', commit_msg)
          pr_number = match.group(0)
          print(pr_number)
