name: Testing conditionals

on:
  workflow_dispatch:
    inputs:
      continue-workflow:
        type: boolean
        default: false
      update-roles:
        type: boolean
        default: false

jobs:
  set-continue-workflow:
    runs-on: ubuntu-latest
    outputs:
      continue-workflow: ${{ steps.decision.outputs.continue-workflow }}
    steps:
      - name: Set job variable
        id: decision
        shell: python
        run: |
          import json
          
          input_var = json.loads(r"""${{ github.event.inputs.continue-workflow }}""")
          print(f"::set-output name=continue-workflow::{input_var}")
      - name: Echo outputs
        run: |
          echo "${{ steps.decision.outputs.continue-workflow }}"

  run-workflow:
    runs-on: ubuntu-latest
    needs: set-continue-workflow
    if: toJson(needs.set-continue-workflow.outputs.continue-workflow) || toJson(github.events.inputs.update-roles)
    steps:
      - name: echo
        run: |
          echo "continue-workflow: ${{ needs.set-continue-workflow.outputs.continue-workflow }}"
          echo "update-roles: ${{ github.event.inputs.update-roles }}"
