# Matrix nesting is not explicitly supported by GitHub Actions
# See: https://github.community/t/proposal-matrix-nesting/16769
#
# Instead, we explicitly write out each matrix config
# See: https://github.community/t/matrix-include/16721/3
name: Playing with matrices

on: [workflow_dispatch]

jobs:
  test-includes-matrix-with-list:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - food: pizza
            flavour: ["pepperoni", "margarita", "hawaiian"]
          - food: "ice cream"
            flavour: ["vanilla", "chocolate", "strawberry"]
    steps:
      - run: |
          echo "Hello World"
          echo '${{ toJson(matrix) }}'
