name: Naming jobs

on:
  workflow_dispatch:

jobs:
  named-job:
    name: '${{ matrix.jobs.cluster }}-${{ matrix.jobs.hub }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [2i2c, utoronto]
        hub: [staging, prod]
    steps:
      - run: echo ${{ matrix.jobs.cluster }}
      - run: echo ${{ matrix.jobs.hub }}
