name: Experiment with PR comments

on:
  pull_request:
    branches:
      - main

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pip install ghapi rich==12.4.4

      - name: Create an output to post as a comment
        id: comment-body
        shell: python
        run: |
          from rich.console import Console
          from rich.table import Table

          console = Console(record=True)
          table = Table(title="Test Table")

          table.add_column("A")
          table.add_column("B")
          table.add_row("1", "2")

          console.print(table)

          with console.capture():
              console.print(table) 

          str_output = console.export_text()
          str_output = str_output.replace("\n", "%0A")

          print(f"::set-output name=comment-body::{str_output}")

      - name: Ascertain if comment exists or not
        id: comment-exists
        shell: python
        run: |
          from ghapi.all import GhApi
          
          api = GhApi(token=r"""${{ secrets.GITHUB_TOKEN }}""")
          issue_number = r"""${{ github.issue.number }}"""
          
          print(issue_number)

      #- name: Post a comment
      #  uses: actions/github-script@v6.1.0
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    script: |
      #      var COMMENT_BODY = process.env.COMMENT_BODY;
      #      
      #      github.rest.issues.createComment({
      #        issue_number: context.issue.number,
      #        owner: context.repo.owner,
      #        repo: context.repo.repo,
      #        body: `${COMMENT_BODY}`
      #      })
      #  env:
      #    COMMENT_BODY: ${{ steps.comment-body.outputs.comment-body }}
