name: Setting env vars from Python

on: [workflow_dispatch]

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - run: |
          python src/setting-env-vars.py
      - name: Generate a matrix 
        shell: python
        run: |
          import os

          cluster_folders = os.listdir("config/clusters")

          matrix = []
          for cluster in cluster_folders:
              matrix.append({"cluster_name": cluster})
          
          env_file = os.getenv("GITHUB_ENV")

          with open(env_file, "a") as f:
              f.write(f"MATRIX={matrix}")
      - run: |
          echo ${{ env.TEST }}
          echo ${{ env.MATRIX }}
