name: Test matrix strategy with single entry

on: [workflow_dispatch]

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=[{'cluster_name': 'nasa-cryo'}]" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.set-matrix.outputs.matrix }}"
      - run: echo ${{ fromJson(steps.set-matrix.outputs.matrix) }}
      - run: echo ${{ toJson(steps.set-matrix.outputs.matrix) }}
  
  use-matrix:
    needs: [set-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.jobs.cluster_name }}
