name: Testing push conditions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-conds:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "workflow dispatch?: ${{ github.event_name == 'workflow_dispatch' }}"
          echo "push to main?: ${{ github.event_name == 'push' && contains(github.ref, 'main') }}"
          echo "push to PR *NOT* from dependabot or pre-commit?: ${{ github.event_name == 'pull_request' && contains(fromJson('["dependabot", "pre-commit"]'), github.head_ref) == 'false' }}"

      - run: |
          echo "combined conditional"
          echo "${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.ref, 'main')) || (github.event_name == 'pull_request' && contains(fromJson('["dependabot", "pre-commit"]'), github.head_ref) == 'false') }}
