# What happens if you reference github.head_ref on a push trigger,
# given that it is only available on a pull_request trigger
name: test head_ref

on: [push, pull_request]

jobs:
  test-head-ref:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.head_ref }}
