name: Testing r2d-action with pr-target trigger

on:
  push:
    branches:
      - main
    paths:
      - "test-image/**"
  pull_request_target:
    paths:
      - "test-image/**"

jobs:
  echo-cond:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event_name == 'pull_request_target' }}"

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY: "quay.io"
          IMAGE_NAME: "sgibson91/test-image"
          LATEST_TAG_OFF: true
          NO_PUSH: "${{ github.event_name == 'pull_request_target' }}"
          REPO2DOCKER_EXTRA_ARGS: "--subdir test-image"
          
