name: Testing r2d-action with pr-target trigger

on:
  push:
    branches:
      - main
    paths:
      - "images/**"
  pull_request_target:
    paths:
      - "images/**"

jobs:
  echo-cond:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event_name == 'pull_request_target' }}"
