# What happens if you reference github.head_ref on a push trigger,
# given that it is only available on a pull_request trigger
#
# Observations:
# - referencing head_ref in a push doesn't cause a failure, it just
#   doesn't come up
name: test head_ref

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-head-ref:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - if: contains(github.head_ref, 'patch')
        run: echo "Hello!"
  # *DO NOT* run this job if the head ref contains the word patch
  conditional-job-not:
    runs-on: unbuntu-latest
    if: contains(github.head_ref, 'patch') == 'false'
    steps:
      - run: echo "No patch here!"
  # *DO* run this job if the head ref contains the word patch
  conditional-job:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'patch')
    steps:
      - run: echo "There's a patch!"
