name: Test Conditional Inputs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        required: false
        default: true

jobs:
  test-cond-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.deploy }}"
      - run: echo "Hello!"
      - if: github.event_name == 'push' || inputs.deploy == 'true'
        run: echo "Hello again!"
